// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NewBusDAL.Models;

public partial class Admin
{
    public int Id { get; set; }
    [ForeignKey("Person")]
    public int PersonId { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }
    public string Token { get; set; }
    public bool Isverified { get; set; } = false;
    public virtual Person Person { get; set; }
    public virtual ICollection<ResetPasswordAdmin> ResetPasswordAdmins { get; set; } = new List<ResetPasswordAdmin>();

    public virtual ICollection<GroupConnections> GroupConnections { get; set; } = new List<GroupConnections>();
public virtual ICollection<AdminConnections> Students{ get; set; } = new List<AdminConnections>();
    public virtual ICollection<Driver> Drivers{ get; set; } = new List<Driver>();
}