// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace NewBusDAL.Models;

public partial class Bus
{
    [JsonIgnore]
    public int Id { get; set; }

    public string PlateNo { get; set; }

    public int? Capacity { get; set; }
    public int Status { get; set; }
    [JsonIgnore]
    public virtual Driver Driver { get; set; } 
}