// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NewBusDAL.Models;

public partial class Driver
{
    public int Id { get; set; }
    [ForeignKey("Person")]
    public int PersonId { get; set; }
    [ForeignKey("Bus")]

    public int BusId { get; set; }

    public double? Lang { get; set; }

    public double? Lat { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }
    [ForeignKey("Admin")]
    public int CreatedByAdminID { get; set; }
    public string Token { get; set; }
    public bool Isverified { get; set; } = false;
    public virtual Admin Admin { get; set; }

    public virtual Bus Bus { get; set; }

    public virtual Person Person { get; set; }
    public virtual ICollection<ResetPasswordDriver> ResetPasswordDrivers { get; set; } = new List<ResetPasswordDriver>();

    public virtual ICollection<GroupConnections> GroupConnections { get; set; } = new List<GroupConnections>();
    public virtual ICollection<Trip> Trips { get; set; } = new List<Trip>();

    public virtual ICollection<DriverConnection> DriverConnections { get; set; } = new List<DriverConnection>();
}