// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace NewBusDAL.Models;

public partial class Faculty
{
    [JsonIgnore]
    public int Id { get; set; }

    public string Name { get; set; }
    [JsonIgnore]

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}