// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace NewBusDAL.Models;

public partial class NewBusContext : DbContext
{
    

    public NewBusContext(DbContextOptions<NewBusContext> options)
        : base(options)
    {
    }
    public virtual DbSet<ResetPasswordDriver> ResetPasswordDrivers { get; set; }
    public virtual DbSet<ResetPasswordAdmin> ResetPasswordAdmins { get; set; }


    public virtual DbSet<ResetPasswordStudent> ResetPasswordStudents { get; set; }
    public virtual DbSet<StationTrip> StationTrips { get; set; }

    public virtual DbSet<RefreshToken>RefreshTokens { get; set; }
    public virtual DbSet<Route> Routes { get; set; } 
public virtual DbSet<DriverConnection> DriverConnections { get; set; }
    public virtual DbSet<StudentConnection> StudentConnections { get; set; }
    public virtual DbSet<GroupConnections> GroupConnections { get; set; }
    public virtual DbSet<Group> Groups { get; set; }
    public virtual DbSet<AdminConnections>AdminConnections { get; set; }
    public virtual DbSet<Admin> Admins { get; set; }
    public virtual DbSet<Bus> Buses { get; set; }
    public virtual DbSet<Driver> Drivers { get; set; }
    public virtual DbSet<Faculty> Faculties { get; set; }
    public virtual DbSet<Person> People { get; set; }
    public virtual DbSet<Student> Students { get; set; }
    public virtual DbSet<Station>Stations { get; set; }
    public virtual DbSet<Trip> Trips { get; set; }
  
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Admin>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Admins__3214EC0711DD1FC9");

           
        });

        modelBuilder.Entity<Bus>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Buses__3214EC07BB401CE8");
        });

        modelBuilder.Entity<Driver>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Drivers__3214EC0776854148");

      

           
        });

        modelBuilder.Entity<Faculty>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Facultie__3214EC07D382E2AE");
        });

        modelBuilder.Entity<Person>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__People__3214EC07BF90B1B6");
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Students__3214EC07EB773F6E");

            entity.HasOne(d => d.Faculty).WithMany(p => p.Students)
                .HasForeignKey(d => d.FacultyId)
                .HasConstraintName("FK__Students__Facult__44FF419A");

        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}