// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NewBusDAL.Models;

public partial class Person
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string SecondName { get; set; }

    public string ThirdName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public int? Age { get; set; }

    public int Gender { get; set; }

    public virtual Admin Admin{ get; set; } 

    public virtual Driver Driver { get; set; }

    public virtual Student Student { get; set; }
}