// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NewBusDAL.Models;

public partial class Student
{
    public int Id { get; set; }
    [ForeignKey("Person")]
    public int? PersonId { get; set; }
    [ForeignKey("Faculty")]
    public int? FacultyId { get; set; }

    public int? Level { get; set; }

    public double? Lang { get; set; }

    public double? Lat { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public virtual Faculty Faculty { get; set; }

    public virtual Person Person { get; set; }
    public string Token { get; set; }
    public bool Isverified { get; set; } = false;
    public virtual ICollection<ResetPasswordStudent> ResetPasswordStudents { get; set; } = new List<ResetPasswordStudent>();

    public virtual ICollection<GroupConnections> GroupConnections { get; set; } = new List<GroupConnections>();
    public virtual ICollection<StudentConnection> StudentConnections { get; set; } = new List<StudentConnection>();
}