// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewBusDAL.Models;

#nullable disable

namespace NewBusDAL.Migrations
{
    [DbContext(typeof(NewBusContext))]
    [Migration("20251205124616_mmmm")]
    partial class mmmm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewBusDAL.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Admins__3214EC0711DD1FC9");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("NewBusDAL.Models.AdminConnections", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("CoonectionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("AdminConnections");
                });

            modelBuilder.Entity("NewBusDAL.Models.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("PlateNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Buses__3214EC07BB401CE8");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("NewBusDAL.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByAdminID")
                        .HasColumnType("int");

                    b.Property<double?>("Lang")
                        .HasColumnType("float");

                    b.Property<double?>("Lat")
                        .HasColumnType("float");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Drivers__3214EC0776854148");

                    b.HasIndex("BusId")
                        .IsUnique();

                    b.HasIndex("CreatedByAdminID");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("NewBusDAL.Models.DriverConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoonectionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.ToTable("DriverConnections");
                });

            modelBuilder.Entity("NewBusDAL.Models.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Facultie__3214EC07D382E2AE");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("NewBusDAL.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("NewBusDAL.Models.GroupConnections", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("DriverId");

                    b.HasIndex("GroupId");

                    b.HasIndex("StudentId");

                    b.ToTable("GroupConnections");
                });

            modelBuilder.Entity("NewBusDAL.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__People__3214EC07BF90B1B6");

                    b.ToTable("People");
                });

            modelBuilder.Entity("NewBusDAL.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RouteId")
                        .HasColumnType("int");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("NewBusDAL.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Latititude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Radius")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("NewBusDAL.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int");

                    b.Property<double?>("Lang")
                        .HasColumnType("float");

                    b.Property<double?>("Lat")
                        .HasColumnType("float");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Students__3214EC07EB773F6E");

                    b.HasIndex("FacultyId");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasFilter("[PersonId] IS NOT NULL");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("NewBusDAL.Models.StudentConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoonectionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentConnections");
                });

            modelBuilder.Entity("NewBusDAL.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancelAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompleteAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByDriverId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCancel")
                        .HasColumnType("bit");

                    b.Property<int>("RouteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusTrip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByDriverId");

                    b.HasIndex("RouteID");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("NewBusDAL.Models.Admin", b =>
                {
                    b.HasOne("NewBusDAL.Models.Person", "Person")
                        .WithOne("Admin")
                        .HasForeignKey("NewBusDAL.Models.Admin", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("NewBusDAL.Models.AdminConnections", b =>
                {
                    b.HasOne("NewBusDAL.Models.Admin", "Admin")
                        .WithMany("Students")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("NewBusDAL.Models.Driver", b =>
                {
                    b.HasOne("NewBusDAL.Models.Bus", "Bus")
                        .WithOne("Driver")
                        .HasForeignKey("NewBusDAL.Models.Driver", "BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewBusDAL.Models.Admin", "Admin")
                        .WithMany("Drivers")
                        .HasForeignKey("CreatedByAdminID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewBusDAL.Models.Person", "Person")
                        .WithOne("Driver")
                        .HasForeignKey("NewBusDAL.Models.Driver", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Bus");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("NewBusDAL.Models.DriverConnection", b =>
                {
                    b.HasOne("NewBusDAL.Models.Driver", "Driver")
                        .WithMany("DriverConnections")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("NewBusDAL.Models.GroupConnections", b =>
                {
                    b.HasOne("NewBusDAL.Models.Admin", "Admin")
                        .WithMany("GroupConnections")
                        .HasForeignKey("AdminId");

                    b.HasOne("NewBusDAL.Models.Driver", "Driver")
                        .WithMany("GroupConnections")
                        .HasForeignKey("DriverId");

                    b.HasOne("NewBusDAL.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewBusDAL.Models.Student", "Student")
                        .WithMany("GroupConnections")
                        .HasForeignKey("StudentId");

                    b.Navigation("Admin");

                    b.Navigation("Driver");

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NewBusDAL.Models.Route", b =>
                {
                    b.HasOne("NewBusDAL.Models.Route", null)
                        .WithMany("Routes")
                        .HasForeignKey("RouteId");
                });

            modelBuilder.Entity("NewBusDAL.Models.Student", b =>
                {
                    b.HasOne("NewBusDAL.Models.Faculty", "Faculty")
                        .WithMany("Students")
                        .HasForeignKey("FacultyId")
                        .HasConstraintName("FK__Students__Facult__44FF419A");

                    b.HasOne("NewBusDAL.Models.Person", "Person")
                        .WithOne("Student")
                        .HasForeignKey("NewBusDAL.Models.Student", "PersonId");

                    b.Navigation("Faculty");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("NewBusDAL.Models.StudentConnection", b =>
                {
                    b.HasOne("NewBusDAL.Models.Student", "Student")
                        .WithMany("StudentConnections")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NewBusDAL.Models.Trip", b =>
                {
                    b.HasOne("NewBusDAL.Models.Driver", "Driver")
                        .WithMany("Trips")
                        .HasForeignKey("CreatedByDriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewBusDAL.Models.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("NewBusDAL.Models.Admin", b =>
                {
                    b.Navigation("Drivers");

                    b.Navigation("GroupConnections");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("NewBusDAL.Models.Bus", b =>
                {
                    b.Navigation("Driver");
                });

            modelBuilder.Entity("NewBusDAL.Models.Driver", b =>
                {
                    b.Navigation("DriverConnections");

                    b.Navigation("GroupConnections");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("NewBusDAL.Models.Faculty", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("NewBusDAL.Models.Person", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Driver");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NewBusDAL.Models.Route", b =>
                {
                    b.Navigation("Routes");
                });

            modelBuilder.Entity("NewBusDAL.Models.Student", b =>
                {
                    b.Navigation("GroupConnections");

                    b.Navigation("StudentConnections");
                });
#pragma warning restore 612, 618
        }
    }
}
